const algomappings = [
    {
      "name": "Homebase Risk Assessment Questionnaire (NYC DSS)",
      "src": "/1. Homebase.png",
      "summary": "An algorithmic tool used during Homebase intake to help assess risk of homelessness and eligibility for services.",
      "use": "Evaluates income, housing history, and other factors to assign a risk score using a logistic regression model.",
      "application": "If you applied for Homebase, this tool assessed your data to determine eligibility for prevention services.",
      "datacard_title1": "Training Data",
      "datacard_text1": "Historical administrative data from NYC DHS and Homebase systems.",
      "datacard_title2": "Input Data",
      "datacard_text2": "Demographics, income, housing history, benefits, and services.",
      "datacard_title3": "Output Data",
      "datacard_text3": "Risk score indicating shelter entry probability.",
      "datacard_title4": "Vendor Involvement",
      "datacard_text4": "Chapin Hall at University of Chicago.",
      "datacard_title5": "Identifying Information",
      "datacard_text5": "Yes \u2014 PII is used."
    },
    {
      "name": "MySchools High School Admissions (NYC DOE)",
      "src": "/2. MySchools Public Schools.png",
      "summary": "Matches students to high schools based on preferences and eligibility using a rule-based system.",
      "use": "Processes ranked applications using the deferred acceptance algorithm.",
      "application": "If you applied via MySchools, this tool determined which school you were offered based on your ranking and criteria.",
      "datacard_title1": "Training Data",
      "datacard_text1": "Not applicable \u2014 rule-based system.",
      "datacard_title2": "Input Data",
      "datacard_text2": "Preferences, eligibility (test scores, residency), seat availability.",
      "datacard_title3": "Output Data",
      "datacard_text3": "Final school offer letter.",
      "datacard_title4": "Vendor Involvement",
      "datacard_text4": "Developed by MIT researchers; maintained by DOE.",
      "datacard_title5": "Identifying Information",
      "datacard_text5": "Yes \u2014 names, IDs, academic records."
    },
    {
      "name": "Idling Complaints Program (NYC DEP)",
      "src": "/3. Idling Complaints.png",
      "summary": "AI tool that analyzes submitted media to determine vehicle idling violations.",
      "use": "Analyzes audio/visual inputs to suggest potential idling violations to staff reviewers.",
      "application": "If someone recorded your car idling, this tool may have been used to evaluate it.",
      "datacard_title1": "Training Data",
      "datacard_text1": "Citizen-submitted media and staff decisions.",
      "datacard_title2": "Input Data",
      "datacard_text2": "Videos and photos via web portal.",
      "datacard_title3": "Output Data",
      "datacard_text3": "Recommendation with confidence score.",
      "datacard_title4": "Vendor Involvement",
      "datacard_text4": "Acuvate.",
      "datacard_title5": "Identifying Information",
      "datacard_text5": "No \u2014 does not use PII."
    },
    {
      "name": "MySchools Medical School Admissions (NYCPS / EMSAS)",
      "src": "/4. MySchools Medical Admissions.png",
      "summary": "Matches applicants to NYC public medical schools based on academic eligibility and preferences.",
      "use": "Centralized process evaluates data to assign placements.",
      "application": "If you applied to a public med school via EMSAS, this tool matched you to a program.",
      "datacard_title1": "Training Data",
      "datacard_text1": "Not applicable \u2014 rules-based.",
      "datacard_title2": "Input Data",
      "datacard_text2": "Academic performance, preferences, eligibility.",
      "datacard_title3": "Output Data",
      "datacard_text3": "School assignment.",
      "datacard_title4": "Vendor Involvement",
      "datacard_text4": "Managed internally by NYCPS.",
      "datacard_title5": "Identifying Information",
      "datacard_text5": "Yes \u2014 includes student identifiers."
    },
    {
      "name": "ChoiceMaker (Immunization Deduplication \u2013 DOHMH)",
      "src": "/5. Choicemaker.png",
      "summary": "Identity-matching tool for merging duplicate vaccine records in NYC.",
      "use": "Uses probabilistic matching on patient records to flag duplicates.",
      "application": "If you had multiple vaccination records, this tool may have merged them.",
      "datacard_title1": "Training Data",
      "datacard_text1": "Human-verified match decisions.",
      "datacard_title2": "Input Data",
      "datacard_text2": "Demographics and vaccine events.",
      "datacard_title3": "Output Data",
      "datacard_text3": "Match score and unified record.",
      "datacard_title4": "Vendor Involvement",
      "datacard_text4": "HLN Consulting.",
      "datacard_title5": "Identifying Information",
      "datacard_text5": "Yes \u2014 name, DOB, provider info."
    },
    {
      "name": "Facial Recognition (DOI)",
      "src": "/6. Facial Recognition.png",
      "summary": "Image-matching tool used in NYC investigations.",
      "use": "Matches images to reference databases with ranked confidence.",
      "application": "If you appeared in surveillance media, this tool may have tried to ID you.",
      "datacard_title1": "Training Data",
      "datacard_text1": "Not disclosed.",
      "datacard_title2": "Input Data",
      "datacard_text2": "Images or video frames.",
      "datacard_title3": "Output Data",
      "datacard_text3": "Ranked identity matches.",
      "datacard_title4": "Vendor Involvement",
      "datacard_text4": "Commercial vendor (undisclosed).",
      "datacard_title5": "Identifying Information",
      "datacard_text5": "Yes \u2014 biometric data used."
    },
    {
      "name": "Evolv Express (NYPD)",
      "src": "/7. Evolv.png",
      "summary": "AI-based weapon detection system deployed in NYC buildings.",
      "use": "Analyzes EM signals and body scans for threats.",
      "application": "If you walked through one of these, your items were scanned.",
      "datacard_title1": "Training Data",
      "datacard_text1": "Proprietary weapon profiles.",
      "datacard_title2": "Input Data",
      "datacard_text2": "EM signals, body scan data.",
      "datacard_title3": "Output Data",
      "datacard_text3": "Threat likelihood alerts.",
      "datacard_title4": "Vendor Involvement",
      "datacard_text4": "Evolv Technology.",
      "datacard_title5": "Identifying Information",
      "datacard_text5": "No \u2014 event-based data only."
    },
    {
      "name": "Patternizr (NYPD)",
      "src": "/8. Patternizr.png",
      "summary": "Detects crime patterns by analyzing police reports for similarities.",
      "use": "Scores narrative + structured data to link related cases.",
      "application": "If involved in a crime report, your case may have been linked to others.",
      "datacard_title1": "Training Data",
      "datacard_text1": "Labeled NYPD case patterns.",
      "datacard_title2": "Input Data",
      "datacard_text2": "Crime details, dates, descriptions.",
      "datacard_title3": "Output Data",
      "datacard_text3": "Similarity scores.",
      "datacard_title4": "Vendor Involvement",
      "datacard_text4": "Built in-house by NYPD.",
      "datacard_title5": "Identifying Information",
      "datacard_text5": "Yes \u2014 PII in reports."
    },
    {
      "name": "Algebra Teaching Assistant (NYCPS)",
      "src": "/9. Algebra Teaching Assistant.png",
      "summary": "AI tool offering hints and feedback to algebra students.",
      "use": "Uses NLP and rules to assist with homework.",
      "application": "If you used a public school algebra tool, this guided your responses.",
      "datacard_title1": "Training Data",
      "datacard_text1": "Not specified.",
      "datacard_title2": "Input Data",
      "datacard_text2": "Student answers.",
      "datacard_title3": "Output Data",
      "datacard_text3": "Hints and feedback.",
      "datacard_title4": "Vendor Involvement",
      "datacard_text4": "Microsoft Research.",
      "datacard_title5": "Identifying Information",
      "datacard_text5": "Yes \u2014 linked to student accounts."
    },
    {
      "name": "MyCity Chatbot (SBS)",
      "src": "/10. MyCity Chatbot.png",
      "summary": "Conversational AI that helps with small business questions.",
      "use": "Uses NLP to respond with resources and links.",
      "application": "If you asked licensing/business questions, this tool answered.",
      "datacard_title1": "Training Data",
      "datacard_text1": "City resource knowledge base.",
      "datacard_title2": "Input Data",
      "datacard_text2": "User queries.",
      "datacard_title3": "Output Data",
      "datacard_text3": "Answer and links.",
      "datacard_title4": "Vendor Involvement",
      "datacard_text4": "Microsoft & EY.",
      "datacard_title5": "Identifying Information",
      "datacard_text5": "Yes \u2014 logged sessions."
    },
    {
      "name": "NYC311 Voice AI (OTI)",
      "src": "/11. 311.png",
      "summary": "Handles 311 calls using AI-powered voice interaction.",
      "use": "Transcribes, interprets, and routes voice input.",
      "application": "If you spoke with automated 311, this tool processed your voice.",
      "datacard_title1": "Training Data",
      "datacard_text1": "Call transcripts.",
      "datacard_title2": "Input Data",
      "datacard_text2": "Caller voice, touch-tone.",
      "datacard_title3": "Output Data",
      "datacard_text3": "Routing and transcription.",
      "datacard_title4": "Vendor Involvement",
      "datacard_text4": "NYC OTI and vendor.",
      "datacard_title5": "Identifying Information",
      "datacard_text5": "Yes \u2014 voice data used."
    },
    {
      "name": "Foodborne Disease Outbreak Detection (DOHMH)",
      "src": "/12. Foodborne.png",
      "summary": "AI system that monitors social media for signs of foodborne illness in NYC.",
      "use": "Scans online reviews for keywords indicating possible outbreaks.",
      "application": "If you posted about food sickness, this tool may have flagged your post for inspection.",
      "datacard_title1": "Training Data",
      "datacard_text1": "Labeled Yelp review data.",
      "datacard_title2": "Input Data",
      "datacard_text2": "Online reviews mentioning restaurants.",
      "datacard_title3": "Output Data",
      "datacard_text3": "Flagged signals for human review.",
      "datacard_title4": "Vendor Involvement",
      "datacard_text4": "Health Department + academic partners.",
      "datacard_title5": "Identifying Information",
      "datacard_text5": "No \u2014 usernames not retained long-term."
    },
    {
      "name": "Google Translate Integration (OTI)",
      "src": "/13. Google Translate.png",
      "summary": "Embedded Google translation service used across NYC.gov websites.",
      "use": "Uses neural machine translation to convert English content to other languages.",
      "application": "If you used the 'Translate' button on NYC.gov, this tool was involved.",
      "datacard_title1": "Training Data",
      "datacard_text1": "Google's multilingual corpus.",
      "datacard_title2": "Input Data",
      "datacard_text2": "English website content.",
      "datacard_title3": "Output Data",
      "datacard_text3": "Translated content.",
      "datacard_title4": "Vendor Involvement",
      "datacard_text4": "Google.",
      "datacard_title5": "Identifying Information",
      "datacard_text5": "No \u2014 session data not retained."
    },
    {
      "name": "ChatGPT (ENDGBV)",
      "src": "/14. ChatGPT ENDGBV.png",
      "summary": "Used to transcribe and summarize conversations for NYC\u2019s domestic and gender-based violence teams.",
      "use": "Converts internal recordings to text summaries using generative AI.",
      "application": "If you contacted ENDGBV services, this may have processed your voice data.",
      "datacard_title1": "Training Data",
      "datacard_text1": "OpenAI\u2019s proprietary corpus.",
      "datacard_title2": "Input Data",
      "datacard_text2": "Internal call transcripts.",
      "datacard_title3": "Output Data",
      "datacard_text3": "Summarized text.",
      "datacard_title4": "Vendor Involvement",
      "datacard_text4": "OpenAI.",
      "datacard_title5": "Identifying Information",
      "datacard_text5": "Yes \u2014 sensitive personal info used."
    },
    {
      "name": "Teacher Evaluation \u2013 Student Growth Model (NYCPS)",
      "src": "/15. Annual Performance Review.png",
      "summary": "Evaluates public school teachers based on predicted vs. actual student performance.",
      "use": "Generates growth percentiles by comparing expected vs. observed test scores.",
      "application": "If you're a teacher, your evaluation may have included this model.",
      "datacard_title1": "Training Data",
      "datacard_text1": "Historical state assessment data.",
      "datacard_title2": "Input Data",
      "datacard_text2": "Test scores, demographics.",
      "datacard_title3": "Output Data",
      "datacard_text3": "Growth percentile.",
      "datacard_title4": "Vendor Involvement",
      "datacard_text4": "Managed by NYCPS.",
      "datacard_title5": "Identifying Information",
      "datacard_text5": "Yes \u2014 includes student and teacher data."
    },
    {
      "name": "Adobe Photoshop (Mayor\u2019s Office)",
      "src": "/16. Photoshop.png",
      "summary": "Adobe\u2019s AI tools used to edit and enhance city media.",
      "use": "Firefly AI is used to remove or fill in visual elements in media productions.",
      "application": "If you appeared in city-created media, your image may have been altered by this tool.",
      "datacard_title1": "Training Data",
      "datacard_text1": "Adobe\u2019s licensed content.",
      "datacard_title2": "Input Data",
      "datacard_text2": "Still images and video from city shoots.",
      "datacard_title3": "Output Data",
      "datacard_text3": "Enhanced or altered visuals.",
      "datacard_title4": "Vendor Involvement",
      "datacard_text4": "Adobe.",
      "datacard_title5": "Identifying Information",
      "datacard_text5": "Yes \u2014 facial and likeness data."
    },
    {
      "name": "EMS Hospital Suggestion Algorithm (FDNY)",
      "src": "/17. EMS Hospital Suggestion.png",
      "summary": "Supports paramedics in selecting the most appropriate NYC hospital for patients.",
      "use": "Factors in symptoms, location, and hospital availability.",
      "application": "If transported by ambulance, this tool influenced where you were taken.",
      "datacard_title1": "Training Data",
      "datacard_text1": "Operational and routing data.",
      "datacard_title2": "Input Data",
      "datacard_text2": "Patient condition, geolocation, hospital availability.",
      "datacard_title3": "Output Data",
      "datacard_text3": "Suggested hospital destination.",
      "datacard_title4": "Vendor Involvement",
      "datacard_text4": "Developed in-house by FDNY.",
      "datacard_title5": "Identifying Information",
      "datacard_text5": "Yes \u2014 includes medical and location data."
    }
  ]

export default algomappings;